"""
Pure summary formatting and output effects for command execution.

This module converts execution summaries to deterministic text/JSON formats
and provides output effects used by the command executor.
"""

from __future__ import annotations

import json
from functools import reduce

from prodbox.cli.effects import WriteStderr, WriteStdout
from prodbox.cli.interpreter import DAGExecutionSummary, EnvironmentError, ExecutionSummary

_PREREQ_FAILURE_PREFIX: str = "Prerequisite failure propagated:"
_TOOL_NOT_FOUND_PREFIX: str = "Tool not found: "
_FILE_NOT_FOUND_PREFIX: str = "File not found: "
_AWS_INVALID_PREFIX: str = "Invalid AWS credentials:"


def _format_duration(seconds: float) -> str:
    """Format duration in human-readable form."""
    match True:
        case _ if seconds < 60:
            return f"{seconds:.2f}s"
        case _ if seconds < 3600:
            minutes = int(seconds // 60)
            secs = int(seconds % 60)
            return f"{minutes}m {secs}s"
        case _:
            hours = int(seconds // 3600)
            minutes = int((seconds % 3600) // 60)
            secs = int(seconds % 60)
            return f"{hours}h {minutes}m {secs}s"


def _is_propagated_prereq_message(message: str) -> bool:
    """Check whether a message is a propagated prerequisite failure."""
    return message.startswith(_PREREQ_FAILURE_PREFIX)


def dag_to_execution_summary(dag_summary: DAGExecutionSummary) -> ExecutionSummary:
    """
    Convert DAGExecutionSummary to a command-level ExecutionSummary.

    This rolls up artifacts/errors from node summaries and preserves deterministic
    node counters generated by the interpreter.
    """
    artifacts = tuple(
        artifact
        for _, node_summary in dag_summary.node_results
        for artifact in node_summary.artifacts
    )
    direct_environment_errors = tuple(
        error
        for _, node_summary in dag_summary.node_results
        for error in node_summary.environment_errors
    )
    parsed_environment_errors = tuple(
        error
        for effect_id, node_summary in dag_summary.node_results
        for error in (_environment_error_from_failure(effect_id, node_summary.message),)
        if not node_summary.success and error is not None
    )
    environment_errors = _dedupe_environment_errors(
        direct_environment_errors + parsed_environment_errors
    )
    return ExecutionSummary(
        exit_code=dag_summary.exit_code,
        message=dag_summary.message,
        total_effects=dag_summary.total_nodes,
        successful_effects=dag_summary.successful_nodes,
        failed_effects=dag_summary.failed_nodes + dag_summary.unexecuted_nodes,
        skipped_effects=dag_summary.skipped_nodes,
        elapsed_seconds=dag_summary.elapsed_seconds,
        artifacts=artifacts,
        environment_errors=environment_errors,
    )


def _environment_error_from_failure(
    effect_id: str,
    message: str,
) -> EnvironmentError | None:
    """Build environment error metadata from deterministic failure messages."""
    match True:
        case _ if _is_propagated_prereq_message(message):
            return None
        case _ if message.startswith(_TOOL_NOT_FOUND_PREFIX):
            tool = message.removeprefix(_TOOL_NOT_FOUND_PREFIX).strip()
            return EnvironmentError(
                tool=tool,
                message=message,
                fix_hint=f"Install {tool}",
                source_effect_id=effect_id,
            )
        case _ if message.startswith(_FILE_NOT_FOUND_PREFIX):
            path = message.removeprefix(_FILE_NOT_FOUND_PREFIX).strip()
            return EnvironmentError(
                tool=path,
                message=message,
                fix_hint=f"Ensure file exists: {path}",
                source_effect_id=effect_id,
            )
        case _ if message.startswith(_AWS_INVALID_PREFIX):
            return EnvironmentError(
                tool="aws",
                message=message,
                fix_hint="Configure AWS credentials via environment variables",
                source_effect_id=effect_id,
            )
        case _:
            return None


def _dedupe_environment_errors(
    errors: tuple[EnvironmentError, ...],
) -> tuple[EnvironmentError, ...]:
    """Deduplicate environment errors by source/message/fix payload."""

    def _step(
        state: tuple[frozenset[tuple[str, str, str]], tuple[EnvironmentError, ...]],
        error: EnvironmentError,
    ) -> tuple[frozenset[tuple[str, str, str]], tuple[EnvironmentError, ...]]:
        key = (error.source_effect_id, error.message, error.fix_hint or "")
        seen, acc = state
        match key in seen:
            case True:
                return seen, acc
            case False:
                return seen | frozenset((key,)), acc + (error,)

    initial: tuple[
        frozenset[tuple[str, str, str]],
        tuple[EnvironmentError, ...],
    ] = frozenset(), ()
    return reduce(_step, errors, initial)[1]


def format_summary(summary: ExecutionSummary) -> str:
    """Format execution summary for human-readable stdout output."""
    match summary.exit_code:
        case 0:
            header = "✅ Command completed successfully"
        case _:
            header = "❌ Command failed"

    lines: list[str] = [
        header,
        f"Message: {summary.message}",
        "",
        "Metrics:",
        f"  Total effects: {summary.total_effects}",
        f"  Successful:    {summary.successful_effects}",
        f"  Failed:        {summary.failed_effects}",
        f"  Skipped:       {summary.skipped_effects}",
        f"  Elapsed:       {_format_duration(summary.elapsed_seconds)}",
    ]

    artifact_lines = [f"  - {artifact}" for artifact in summary.artifacts]
    match bool(artifact_lines):
        case True:
            lines.extend(["", "Artifacts:", *artifact_lines])
        case False:
            pass

    error_lines = [
        line
        for error in summary.environment_errors
        for line in (
            f"  - Tool: {error.tool}",
            f"    Effect: {error.source_effect_id}",
            f"    Message: {error.message}",
        )
    ]
    match bool(error_lines):
        case True:
            lines.extend(["", "Environment Errors:", *error_lines])
        case False:
            pass

    fix_lines = [
        f"  - {label}: {hint}" for label, hint in _manual_fix_entries(summary.environment_errors)
    ]
    match bool(fix_lines):
        case True:
            lines.extend(["", "Manual env changes needed:", *fix_lines])
        case False:
            pass

    return "\n".join(lines) + "\n"


def format_summary_json(summary: ExecutionSummary) -> str:
    """Format execution summary as deterministic JSON."""
    manual_fixes = tuple(
        {"label": label, "fix_hint": hint}
        for label, hint in _manual_fix_entries(summary.environment_errors)
    )
    data = {
        "exit_code": summary.exit_code,
        "message": summary.message,
        "total_effects": summary.total_effects,
        "successful_effects": summary.successful_effects,
        "failed_effects": summary.failed_effects,
        "skipped_effects": summary.skipped_effects,
        "elapsed_seconds": round(summary.elapsed_seconds, 3),
        "artifacts": [str(path) for path in summary.artifacts],
        "environment_errors": [_error_to_json(error) for error in summary.environment_errors],
        "manual_env_changes": manual_fixes,
    }
    return json.dumps(data, indent=2)


def _error_to_json(error: EnvironmentError) -> dict[str, str | None]:
    """Convert EnvironmentError to JSON-safe mapping."""
    return {
        "tool": error.tool,
        "message": error.message,
        "fix_hint": error.fix_hint,
        "source_effect_id": error.source_effect_id,
    }


def _manual_fix_entries(
    errors: tuple[EnvironmentError, ...],
) -> tuple[tuple[str, str], ...]:
    """Extract and deduplicate manual fix entries from environment errors."""
    raw_entries = tuple(
        (error.source_effect_id or error.tool, hint)
        for error in errors
        for hint in ((error.fix_hint or ""),)
        if hint
    )
    return _dedupe_manual_fix_entries(raw_entries)


def _dedupe_manual_fix_entries(
    entries: tuple[tuple[str, str], ...],
) -> tuple[tuple[str, str], ...]:
    """Deduplicate entries by hint text while preserving first-seen order."""

    def _step(
        state: tuple[frozenset[str], tuple[tuple[str, str], ...]],
        entry: tuple[str, str],
    ) -> tuple[frozenset[str], tuple[tuple[str, str], ...]]:
        seen, acc = state
        label, hint = entry
        match hint in seen:
            case True:
                return seen, acc
            case False:
                return seen | frozenset((hint,)), acc + ((label, hint),)

    initial: tuple[frozenset[str], tuple[tuple[str, str], ...]] = frozenset(), ()
    return reduce(_step, entries, initial)[1]


def format_dag_failure_report(dag_summary: DAGExecutionSummary) -> str:
    """Format failed DAG nodes for stderr when command execution fails."""
    failed_nodes = tuple(
        (effect_id, node_summary.message)
        for effect_id, node_summary in dag_summary.node_results
        if not node_summary.success
    )
    propagated = tuple(
        (effect_id, message)
        for effect_id, message in failed_nodes
        if _is_propagated_prereq_message(message)
    )
    root_failures = tuple(
        (effect_id, message)
        for effect_id, message in failed_nodes
        if not _is_propagated_prereq_message(message)
    )

    lines: list[str] = ["Failure Details:"]
    match bool(root_failures):
        case True:
            lines.append("  Root-cause failures:")
            lines.extend([f"    - {effect_id}: {message}" for effect_id, message in root_failures])
        case False:
            pass
    match bool(propagated):
        case True:
            lines.append("  Propagated prerequisite failures:")
            lines.extend([f"    - {effect_id}: {message}" for effect_id, message in propagated])
        case False:
            pass
    match bool(root_failures or propagated):
        case True:
            pass
        case False:
            lines.append("  No failed nodes were recorded.")

    return "\n".join(lines) + "\n"


def display_summary(summary: ExecutionSummary) -> WriteStdout:
    """Create stdout effect for formatted execution summary."""
    return WriteStdout(
        effect_id="display_summary",
        description="Display execution summary",
        text=format_summary(summary),
    )


def display_dag_summary(dag_summary: DAGExecutionSummary) -> WriteStdout:
    """Create stdout effect for formatted DAG summary."""
    return display_summary(dag_to_execution_summary(dag_summary))


def display_dag_failure_report(dag_summary: DAGExecutionSummary) -> WriteStderr | None:
    """Create stderr effect with DAG failure details when exit code is non-zero."""
    match dag_summary.exit_code:
        case 0:
            return None
        case _:
            return WriteStderr(
                effect_id="display_dag_failure_report",
                description="Display DAG failure details",
                text=format_dag_failure_report(dag_summary),
            )


__all__ = [
    "dag_to_execution_summary",
    "format_summary",
    "format_summary_json",
    "format_dag_failure_report",
    "display_summary",
    "display_dag_summary",
    "display_dag_failure_report",
]
