apiVersion: v1
kind: Secret
metadata:
  name: gateway-aws-credentials
  labels:
    {{- include "gateway.labels" . | nindent 4 }}
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: {{ .Values.aws.accessKeyId | quote }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.aws.secretAccessKey | quote }}
  AWS_SESSION_TOKEN: {{ .Values.aws.sessionToken | quote }}
