apiVersion: v1
kind: Secret
metadata:
  name: gateway-prodbox-config
  labels:
    {{- include "gateway.labels" . | nindent 4 }}
type: Opaque
stringData:
  prodbox-config.json: |-
    {
      "aws": {
        "access_key_id": {{ .Values.aws.accessKeyId | quote }},
        "secret_access_key": {{ .Values.aws.secretAccessKey | quote }},
        {{- if .Values.aws.sessionToken }}
        "session_token": {{ .Values.aws.sessionToken | quote }},
        {{- else }}
        "session_token": null,
        {{- end }}
        "region": {{ .Values.dnsWriteGate.awsRegion | quote }}
      },
      "route53": {
        "zone_id": {{ .Values.dnsWriteGate.zoneId | quote }}
      },
      "domain": {
        "demo_fqdn": {{ .Values.dnsWriteGate.fqdn | quote }},
        "demo_ttl": {{ .Values.dnsWriteGate.ttl }},
        "vscode_fqdn": null
      },
      "acme": {
        "email": "gateway@invalid",
        "server": "https://acme-staging-v02.api.letsencrypt.org/directory"
      },
      "deployment": {
        "dev_mode": true,
        "bootstrap_public_ip_override": null,
        "pulumi_enable_dns_bootstrap": false
      }
    }
