apiVersion: v1
kind: ConfigMap
metadata:
  name: keycloak-realm-import
  labels:
    {{- include "keycloak.labels" . | nindent 4 }}
data:
  realm.json: |
    {
      "realm": {{ .Values.keycloak.realmName | quote }},
      "enabled": true,
      "displayName": "prodbox",
      "sslRequired": "none",
      "registrationAllowed": false,
      "loginWithEmailAllowed": true,
      "clients": [
        {
          "clientId": {{ .Values.nginx.clientId | quote }},
          "secret": {{ .Values.nginx.clientSecret | quote }},
          "enabled": true,
          "publicClient": false,
          "protocol": "openid-connect",
          "standardFlowEnabled": true,
          "directAccessGrantsEnabled": false,
          "redirectUris": [
            {{ printf "https://%s/auth/callback" .Values.keycloak.publicHost | quote }}
          ],
          "webOrigins": [
            {{ printf "https://%s" .Values.keycloak.publicHost | quote }}
          ]
        }
      ]
    }
