apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Values.gateway.tlsSecretName | quote }}
  labels:
    {{- include "keycloak.labels" . | nindent 4 }}
spec:
  secretName: {{ .Values.gateway.tlsSecretName | quote }}
  issuerRef:
    kind: ClusterIssuer
    name: {{ .Values.gateway.clusterIssuer | quote }}
  dnsNames:
    - {{ .Values.keycloak.publicHost | quote }}
    - {{ .Values.gateway.vscodePublicHost | quote }}
    - {{ .Values.gateway.apiPublicHost | quote }}
    - {{ .Values.gateway.websocketPublicHost | quote }}
---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: {{ .Values.gateway.name | quote }}
  labels:
    {{- include "keycloak.labels" . | nindent 4 }}
spec:
  gatewayClassName: {{ .Values.gateway.className | quote }}
  listeners:
    - name: {{ .Values.gateway.listenerName | quote }}
      hostname: {{ .Values.keycloak.publicHost | quote }}
      port: 443
      protocol: HTTPS
      tls:
        mode: Terminate
        certificateRefs:
          - kind: Secret
            name: {{ .Values.gateway.tlsSecretName | quote }}
      allowedRoutes:
        namespaces:
          from: All
    - name: vscode-https
      hostname: {{ .Values.gateway.vscodePublicHost | quote }}
      port: 443
      protocol: HTTPS
      tls:
        mode: Terminate
        certificateRefs:
          - kind: Secret
            name: {{ .Values.gateway.tlsSecretName | quote }}
      allowedRoutes:
        namespaces:
          from: All
    - name: {{ .Values.gateway.apiListenerName | quote }}
      hostname: {{ .Values.gateway.apiPublicHost | quote }}
      port: 443
      protocol: HTTPS
      tls:
        mode: Terminate
        certificateRefs:
          - kind: Secret
            name: {{ .Values.gateway.tlsSecretName | quote }}
      allowedRoutes:
        namespaces:
          from: All
    - name: {{ .Values.gateway.websocketListenerName | quote }}
      hostname: {{ .Values.gateway.websocketPublicHost | quote }}
      port: 443
      protocol: HTTPS
      tls:
        mode: Terminate
        certificateRefs:
          - kind: Secret
            name: {{ .Values.gateway.tlsSecretName | quote }}
      allowedRoutes:
        namespaces:
          from: All
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ .Values.gateway.routeName | quote }}
  labels:
    {{- include "keycloak.labels" . | nindent 4 }}
spec:
  parentRefs:
    - name: {{ .Values.gateway.name | quote }}
      sectionName: {{ .Values.gateway.listenerName | quote }}
  hostnames:
    - {{ .Values.keycloak.publicHost | quote }}
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /realms
        - path:
            type: PathPrefix
            value: /resources
      backendRefs:
        - name: keycloak
          port: 8080
