apiVersion: v1
kind: Secret
metadata:
  name: keycloak-runtime
  labels:
    {{- include "keycloak.labels" . | nindent 4 }}
type: Opaque
stringData:
  KEYCLOAK_ADMIN: {{ .Values.keycloak.adminUser | quote }}
  KEYCLOAK_ADMIN_PASSWORD: {{ .Values.keycloak.adminPassword | quote }}
{{- if .Values.smtp.enabled }}
---
apiVersion: v1
kind: Secret
metadata:
  name: keycloak-smtp
  labels:
    {{- include "keycloak.labels" . | nindent 4 }}
  annotations:
    prodbox.io/ses-pulumi-source: pulumi/aws-ses
type: Opaque
stringData:
  KC_SMTP_HOST: {{ .Values.smtp.host | quote }}
  KC_SMTP_PORT: {{ .Values.smtp.port | quote }}
  KC_SMTP_FROM: {{ .Values.smtp.from | quote }}
  KC_SMTP_FROM_DISPLAY_NAME: {{ .Values.smtp.fromDisplayName | quote }}
  KC_SMTP_REPLY_TO: {{ .Values.smtp.replyTo | quote }}
  KC_SMTP_USER: {{ .Values.smtp.user | quote }}
  KC_SMTP_PASSWORD: {{ .Values.smtp.password | quote }}
{{- end }}
