apiVersion: v1
kind: Secret
metadata:
  name: keycloak-runtime
  labels:
    {{- include "keycloak.labels" . | nindent 4 }}
type: Opaque
stringData:
  KEYCLOAK_ADMIN: {{ .Values.keycloak.adminUser | quote }}
  KEYCLOAK_ADMIN_PASSWORD: {{ .Values.keycloak.adminPassword | quote }}
