apiVersion: v1
kind: ServiceAccount
metadata:
  name: keycloak
  labels:
    {{- include "keycloak.labels" . | nindent 4 }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: oidc-session-validation-agent
  labels:
    {{- include "keycloak.labels" . | nindent 4 }}
    app.kubernetes.io/component: oidc-session-validation-agent
