apiVersion: apps/v1
kind: Deployment
metadata:
  name: websocket
  labels:
    {{- include "websocket.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: websocket
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "websocket.labels" . | nindent 8 }}
    spec:
      terminationGracePeriodSeconds: 30
      {{- if .Values.podAntiAffinity.enabled }}
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchLabels:
                  app.kubernetes.io/name: websocket
                  app.kubernetes.io/instance: {{ .Release.Name }}
              topologyKey: kubernetes.io/hostname
      {{- end }}
      containers:
        - name: websocket
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: Always
          args: ["workload", "start", "--config", "/etc/workload/config.dhall"]
          volumeMounts:
            - name: workload-config
              mountPath: /etc/workload/config.dhall
              subPath: config.dhall
              readOnly: true
          ports:
            - name: http
              containerPort: {{ .Values.websocket.port }}
          lifecycle:
            preStop:
              httpGet:
                path: /drain
                port: http
          readinessProbe:
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 15
            periodSeconds: 10
      volumes:
        - name: workload-config
          configMap:
            name: websocket-config
