apiVersion: v1
kind: Service
metadata:
  name: websocket
  labels:
    {{- include "websocket.labels" . | nindent 4 }}
spec:
  selector:
    app.kubernetes.io/name: websocket
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - name: http
      port: {{ .Values.websocket.port }}
      targetPort: http
