{-# LANGUAGE OverloadedStrings #-}

-- | Sprint 7.5.c.ii — EKS containerd registry-mirror config injection.
--
-- The home substrate routes @127.0.0.1:30080@ chart-image refs to its
-- in-cluster Harbor via RKE2's @/etc/rancher/rke2/registries.yaml@ —
-- a mechanism EKS does not expose. This module renders a privileged
-- DaemonSet manifest that, on every EKS node:
--
--   1. Ensures @/etc/containerd/config.toml@ enables
--      @config_path = "/etc/containerd/certs.d"@ under the registry
--      plugin section. Amazon Linux 2023 EKS AMIs from late 2024
--      onward already enable this; older AMIs need the patch.
--   2. Writes a registry-mirror drop-in at
--      @/etc/containerd/certs.d/127.0.0.1:30080/hosts.toml@ pointing
--      at the in-cluster Harbor NodePort with @skip_verify = true@
--      (HTTP-only, no TLS).
--   3. Restarts containerd via @nsenter@ against the host PID
--      namespace **only when (1) or (2) actually changed something**
--      so the DaemonSet is idempotent on subsequent rollouts.
--
-- After the drop-in lands, containerd resolves @127.0.0.1:30080@
-- chart-image pulls through the EKS-side Harbor NodePort exposed by
-- Sprint @7.5.c.iii@. The same chart-image refs work unchanged across
-- both substrates per the substrate-equivalence doctrine in
-- @DEVELOPMENT_PLAN/substrates.md@.
--
-- This module is renderer-only. The effectful wiring into
-- @Prodbox.Lib.AwsSubstratePlatform.ensureAwsSubstratePlatformRuntime@
-- lands in Sprint @7.5.c.iii@.
module Prodbox.Lib.EksContainerdMirror
  ( ContainerdMirrorConfig (..)
  , defaultProdboxMirrorConfig
  , eksContainerdMirrorDaemonSetManifest
  , eksContainerdMirrorBootstrapScript
  )
where

import Data.Aeson
  ( Value
  , object
  , (.=)
  )
import Data.Aeson.Key qualified as Key
import Data.List (intercalate)

-- | Configuration for the EKS containerd registry-mirror drop-in.
data ContainerdMirrorConfig = ContainerdMirrorConfig
  { mirrorRegistryHostPort :: String
  -- ^ The @host:port@ pair chart-image refs use, e.g.
  -- @127.0.0.1:30080@. The drop-in lands at
  -- @/etc/containerd/certs.d/<this>/hosts.toml@.
  , mirrorTargetEndpoint :: String
  -- ^ The HTTP endpoint containerd is told to fetch from, e.g.
  -- @http://127.0.0.1:30080@. On EKS this resolves to the in-cluster
  -- Harbor NodePort via the host's iptables rules; the Harbor service
  -- exposed by Sprint @7.5.c.iii@ binds NodePort @30080@.
  , mirrorRewritePrefix :: String
  -- ^ Path-prefix containerd prepends when rewriting requests, e.g.
  -- @"prodbox/"@. Mirrors the home substrate's @registries.yaml@
  -- @rewrite \"^(.*)$\": \"prodbox/$1\"@ rule.
  , mirrorNamespace :: String
  -- ^ Kubernetes namespace the DaemonSet lands in. Defaults to
  -- @kube-system@ — adjacent to the AWS Load Balancer Controller.
  , mirrorDaemonSetName :: String
  -- ^ @metadata.name@ for the DaemonSet.
  , mirrorBootstrapImage :: String
  -- ^ Container image for the init container that writes the drop-in
  -- and (conditionally) restarts containerd. Needs only @nsenter@ +
  -- @sh@; @public.ecr.aws/eks-distro/kubernetes/pause:3.9@ works as a
  -- pause for the long-running pod, while @docker.io/alpine:3.20@ (or
  -- @public.ecr.aws/docker/library/alpine:3.20@) suffices for the
  -- bootstrap init container.
  }
  deriving (Eq, Show)

-- | Default mirror config matching the home substrate's
-- @127.0.0.1:30080 -> in-cluster Harbor@ contract. The DaemonSet
-- lands as @prodbox-containerd-mirror@ in @kube-system@.
defaultProdboxMirrorConfig :: ContainerdMirrorConfig
defaultProdboxMirrorConfig =
  ContainerdMirrorConfig
    { mirrorRegistryHostPort = "127.0.0.1:30080"
    , mirrorTargetEndpoint = "http://127.0.0.1:30080"
    , mirrorRewritePrefix = "prodbox/"
    , mirrorNamespace = "kube-system"
    , mirrorDaemonSetName = "prodbox-containerd-mirror"
    , mirrorBootstrapImage = "public.ecr.aws/docker/library/alpine:3.20"
    }

-- | Render the @hosts.toml@ drop-in body that lands at
-- @/etc/containerd/certs.d/<host>/hosts.toml@ on every node.
--
-- Format follows containerd 1.7+'s host-config schema; the
-- @capabilities@ list is mandatory ("pull", "resolve") so containerd
-- treats the mirror as eligible for image fetches.
eksContainerdMirrorHostsToml :: ContainerdMirrorConfig -> String
eksContainerdMirrorHostsToml config =
  intercalate
    "\n"
    [ "# Generated by Prodbox Sprint 7.5.c.ii — do not edit by hand."
    , "# Routes " ++ mirrorRegistryHostPort config ++ " image pulls to the"
    , "# in-cluster Harbor NodePort installed by Sprint 7.5.c.iii."
    , "server = \"" ++ mirrorTargetEndpoint config ++ "\""
    , ""
    , "[host.\"" ++ mirrorTargetEndpoint config ++ "\"]"
    , "  capabilities = [\"pull\", \"resolve\"]"
    , "  skip_verify = true"
    , ""
    ]

-- | Render the bootstrap @sh@ script the init container runs on each
-- EKS node. The script writes the drop-in, conditionally patches the
-- main containerd config to enable @config_path@, and restarts
-- containerd via @nsenter@ ONLY when one of the writes actually
-- changed something on disk.
--
-- Exposed for unit-test inspection alongside
-- 'eksContainerdMirrorDaemonSetManifest'.
eksContainerdMirrorBootstrapScript :: ContainerdMirrorConfig -> String
eksContainerdMirrorBootstrapScript config =
  intercalate
    "\n"
    [ "#!/bin/sh"
    , "set -eu"
    , ""
    , "HOST=\"" ++ mirrorRegistryHostPort config ++ "\""
    , "DROPIN_DIR=\"/host/etc/containerd/certs.d/${HOST}\""
    , "DROPIN_PATH=\"${DROPIN_DIR}/hosts.toml\""
    , "CONFIG_PATH=\"/host/etc/containerd/config.toml\""
    , "RESTART_NEEDED=0"
    , ""
    , "# 1. Ensure config_path is set in the main containerd config."
    , "if ! grep -qE '^[[:space:]]*config_path[[:space:]]*=[[:space:]]*\"/etc/containerd/certs.d\"' \"${CONFIG_PATH}\"; then"
    , "  echo \"prodbox-containerd-mirror: enabling config_path in ${CONFIG_PATH}\""
    , "  # Append a registry section if one isn't already present."
    , "  if ! grep -q '\\[plugins.\"io.containerd.grpc.v1.cri\".registry\\]' \"${CONFIG_PATH}\"; then"
    , "    {"
    , "      echo ''"
    , "      echo '[plugins.\"io.containerd.grpc.v1.cri\".registry]'"
    , "      echo '  config_path = \"/etc/containerd/certs.d\"'"
    , "    } >> \"${CONFIG_PATH}\""
    , "  else"
    , "    # registry section exists but lacks config_path — append within it."
    , "    awk '"
    , "      BEGIN { inserted = 0 }"
    , "      /\\[plugins.\"io.containerd.grpc.v1.cri\".registry\\]/ {"
    , "        printf \"%s\\n\", $0"
    , "        printf \"%s\\n\", \"  config_path = \\\"/etc/containerd/certs.d\\\"\""
    , "        inserted = 1"
    , "        next"
    , "      }"
    , "      { printf \"%s\\n\", $0 }"
    , "    ' \"${CONFIG_PATH}\" > \"${CONFIG_PATH}.prodbox-tmp\" && mv \"${CONFIG_PATH}.prodbox-tmp\" \"${CONFIG_PATH}\""
    , "  fi"
    , "  RESTART_NEEDED=1"
    , "fi"
    , ""
    , "# 2. Write the mirror drop-in (idempotent: only when the content differs)."
    , "mkdir -p \"${DROPIN_DIR}\""
    , "TARGET_HOSTS=$(cat <<'EOF_HOSTS'"
    , eksContainerdMirrorHostsToml config
    , "EOF_HOSTS"
    , ")"
    , "if [ ! -f \"${DROPIN_PATH}\" ] || ! printf '%s' \"${TARGET_HOSTS}\" | cmp -s - \"${DROPIN_PATH}\"; then"
    , "  echo \"prodbox-containerd-mirror: writing ${DROPIN_PATH}\""
    , "  printf '%s' \"${TARGET_HOSTS}\" > \"${DROPIN_PATH}\""
    , "  RESTART_NEEDED=1"
    , "fi"
    , ""
    , "# 3. Restart containerd only if we changed something."
    , "if [ \"${RESTART_NEEDED}\" = \"1\" ]; then"
    , "  echo \"prodbox-containerd-mirror: restarting containerd via host PID namespace\""
    , "  nsenter --target 1 --mount --uts --ipc --net --pid -- systemctl restart containerd"
    , "else"
    , "  echo \"prodbox-containerd-mirror: containerd config already in place; no restart\""
    , "fi"
    , ""
    , "echo \"prodbox-containerd-mirror: bootstrap complete\""
    , ""
    ]

-- | Render the Kubernetes DaemonSet manifest that schedules the
-- bootstrap script onto every EKS node. The DaemonSet uses
-- @hostNetwork@, @hostPID@, and a @hostPath@ mount of @/etc@ so the
-- init container can read/write the host's containerd config; the
-- main container is a long-running @pause@-equivalent that keeps the
-- pod alive (so kubelet does not re-schedule it).
--
-- Wrap in a @v1/List@ for @kubectl apply -f@ — see
-- @Prodbox.Lib.AwsSubstratePlatform.ensureAwsSubstrateAcmeRuntime@
-- for the wrapping pattern.
eksContainerdMirrorDaemonSetManifest :: ContainerdMirrorConfig -> Value
eksContainerdMirrorDaemonSetManifest config =
  object
    [ "apiVersion" .= ("apps/v1" :: String)
    , "kind" .= ("DaemonSet" :: String)
    , "metadata"
        .= object
          [ "name" .= mirrorDaemonSetName config
          , "namespace" .= mirrorNamespace config
          , "labels"
              .= object
                [ Key.fromString "app.kubernetes.io/name" .= mirrorDaemonSetName config
                , Key.fromString "app.kubernetes.io/managed-by" .= ("prodbox" :: String)
                , Key.fromString "prodbox.io/sprint" .= ("7.5.c.ii" :: String)
                ]
          ]
    , "spec"
        .= object
          [ "selector"
              .= object
                [ "matchLabels"
                    .= object
                      [ Key.fromString "app.kubernetes.io/name" .= mirrorDaemonSetName config
                      ]
                ]
          , "template"
              .= object
                [ "metadata"
                    .= object
                      [ "labels"
                          .= object
                            [ Key.fromString "app.kubernetes.io/name" .= mirrorDaemonSetName config
                            ]
                      ]
                , "spec"
                    .= object
                      [ "hostNetwork" .= True
                      , "hostPID" .= True
                      , "tolerations"
                          .= [ object
                                 [ "operator" .= ("Exists" :: String)
                                 ]
                             ]
                      , "initContainers"
                          .= [ object
                                 [ "name" .= ("bootstrap" :: String)
                                 , "image" .= mirrorBootstrapImage config
                                 , "securityContext"
                                     .= object
                                       [ "privileged" .= True
                                       ]
                                 , "command" .= (["/bin/sh", "-c"] :: [String])
                                 , "args" .= [eksContainerdMirrorBootstrapScript config]
                                 , "volumeMounts"
                                     .= [ object
                                            [ "name" .= ("host-etc" :: String)
                                            , "mountPath" .= ("/host/etc" :: String)
                                            ]
                                        ]
                                 ]
                             ]
                      , "containers"
                          .= [ object
                                 [ "name" .= ("pause" :: String)
                                 , "image" .= ("public.ecr.aws/eks-distro/kubernetes/pause:3.9" :: String)
                                 , "resources"
                                     .= object
                                       [ "requests"
                                           .= object
                                             [ "cpu" .= ("5m" :: String)
                                             , "memory" .= ("16Mi" :: String)
                                             ]
                                       , "limits"
                                           .= object
                                             [ "memory" .= ("32Mi" :: String)
                                             ]
                                       ]
                                 ]
                             ]
                      , "volumes"
                          .= [ object
                                 [ "name" .= ("host-etc" :: String)
                                 , "hostPath"
                                     .= object
                                       [ "path" .= ("/etc" :: String)
                                       , "type" .= ("Directory" :: String)
                                       ]
                                 ]
                             ]
                      ]
                ]
          ]
    ]
