global:
  namespace: default
  rootChart: keycloak

replicaCount: 2

podAntiAffinity:
  enabled: true

image:
  repository: 127.0.0.1:30080/prodbox/keycloak-mirror
  tag: "26.0.0"

keycloak:
  adminUser: admin
  adminPassword: change-me
  publicHost: vscode.example.com
  relativePath: /auth
  realmName: prodbox

postgres:
  host: keycloak-postgres
  database: keycloak
  username: keycloak
  password: change-me

nginx:
  clientId: vscode-nginx
  clientSecret: change-me
