.TH PRODBOX_tls_retention 1
.SH NAME
prodbox-tls-retention \- Dedicated tls-retention runtime
.SH SYNOPSIS
.B prodbox tls-retention
.SH DESCRIPTION
Commands for the physically separated tls-retention process.
.SH SUBCOMMANDS
.TP
\fBstart\fR
Start tls-retention
.SH EXAMPLES
.TP
\fBprodbox tls-retention start --config /etc/tls-retention/config/config.dhall\fR
Start tls-retention.
