.TH PRODBOX_bootstrap_broker 1
.SH NAME
prodbox-bootstrap-broker \- Pre-Vault Bootstrap Broker operations
.SH SYNOPSIS
.B prodbox bootstrap-broker
.SH DESCRIPTION
Dedicated pre-Vault Bootstrap Broker runtime commands.
.SH SUBCOMMANDS
.TP
\fBstart\fR
Start the Bootstrap Broker
.SH EXAMPLES
.TP
\fBprodbox bootstrap-broker start --config /etc/bootstrap-broker/config/config.dhall\fR
Start the dedicated Bootstrap Broker runtime.
