.TH PRODBOX_provider_worker 1
.SH NAME
prodbox-provider-worker \- Dedicated provider-worker runtime
.SH SYNOPSIS
.B prodbox provider-worker
.SH DESCRIPTION
Commands for the physically separated provider-worker process.
.SH SUBCOMMANDS
.TP
\fBstart\fR
Start provider-worker
.SH EXAMPLES
.TP
\fBprodbox provider-worker start --config /etc/provider-worker/config/config.dhall\fR
Start provider-worker.
