.TH PRODBOX_workload 1
.SH NAME
prodbox-workload \- Internal public workload runtime
.SH SYNOPSIS
.B prodbox workload
.SH DESCRIPTION
Internal workload daemon commands.
.SH SUBCOMMANDS
.TP
\fBstart\fR
Start internal workload runtime
.SH EXAMPLES
.TP
\fBprodbox workload start\fR
Start the internal workload runtime.
