.TH PRODBOX_target_secret_agent 1
.SH NAME
prodbox-target-secret-agent \- Dedicated target-secret-agent runtime
.SH SYNOPSIS
.B prodbox target-secret-agent
.SH DESCRIPTION
Commands for the physically separated target-secret-agent process.
.SH SUBCOMMANDS
.TP
\fBstart\fR
Start target-secret-agent
.SH EXAMPLES
.TP
\fBprodbox target-secret-agent start --config /etc/target-secret-agent/config/config.dhall\fR
Start target-secret-agent.
