.TH PRODBOX_charts 1
.SH NAME
prodbox-charts \- Bespoke Helm chart lifecycle
.SH SYNOPSIS
.B prodbox charts
.SH DESCRIPTION
Supported chart lifecycle commands.
.SH SUBCOMMANDS
.TP
\fBlist\fR
List supported charts
.TP
\fBstatus\fR
Show detailed chart status
.TP
\fBdeploy\fR
Deploy a root chart stack
.TP
\fBdelete\fR
Delete a root chart stack
.SH EXAMPLES
.TP
\fBprodbox charts list\fR
List supported root charts.
