.TH PRODBOX_authority_backup 1
.SH NAME
prodbox-authority-backup \- Dedicated authority-backup runtime
.SH SYNOPSIS
.B prodbox authority-backup
.SH DESCRIPTION
Commands for the physically separated authority-backup process.
.SH SUBCOMMANDS
.TP
\fBstart\fR
Start authority-backup
.SH EXAMPLES
.TP
\fBprodbox authority-backup start --config /etc/authority-backup/config/config.dhall\fR
Start authority-backup.
