apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secrets.application.name }}
  labels:
    {{- include "keycloak-postgres.labels" . | nindent 4 }}
    application: spilo
    cluster-name: {{ .Values.cluster.name | quote }}
    team: {{ .Values.cluster.teamId | quote }}
type: Opaque
stringData:
  username: {{ .Values.secrets.application.username | quote }}
  password: {{ .Values.secrets.application.password | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secrets.superuser.name }}
  labels:
    {{- include "keycloak-postgres.labels" . | nindent 4 }}
    application: spilo
    cluster-name: {{ .Values.cluster.name | quote }}
    team: {{ .Values.cluster.teamId | quote }}
type: Opaque
stringData:
  username: {{ .Values.secrets.superuser.username | quote }}
  password: {{ .Values.secrets.superuser.password | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secrets.standby.name }}
  labels:
    {{- include "keycloak-postgres.labels" . | nindent 4 }}
    application: spilo
    cluster-name: {{ .Values.cluster.name | quote }}
    team: {{ .Values.cluster.teamId | quote }}
type: Opaque
stringData:
  username: {{ .Values.secrets.standby.username | quote }}
  password: {{ .Values.secrets.standby.password | quote }}
