global:
  namespace: default
  rootChart: keycloak

cluster:
  name: prodbox-keycloak-postgres
  teamId: prodbox
  instances: 3

image:
  spilo:
    repository: 127.0.0.1:30080/prodbox/spilo-17-mirror
    tag: "4.0-p3"

postgres:
  version: "17"
  database: keycloak
  username: keycloak
  credentialsSecretName: keycloak.prodbox-keycloak-postgres.credentials.postgresql.acid.zalan.do

secrets:
  application:
    name: keycloak.prodbox-keycloak-postgres.credentials.postgresql.acid.zalan.do
    username: keycloak
    password: change-me
  superuser:
    name: postgres.prodbox-keycloak-postgres.credentials.postgresql.acid.zalan.do
    username: postgres
    password: change-me
  standby:
    name: standby.prodbox-keycloak-postgres.credentials.postgresql.acid.zalan.do
    username: standby
    password: change-me

storage:
  className: manual
  size: 20Gi
  bindings:
    - ordinal: 0
      pvcName: pgdata-prodbox-keycloak-postgres-0
    - ordinal: 1
      pvcName: pgdata-prodbox-keycloak-postgres-1
    - ordinal: 2
      pvcName: pgdata-prodbox-keycloak-postgres-2

security:
  runAsUser: 101
  runAsGroup: 103
  fsGroup: 103
