global:
  namespace: default
  rootChart: keycloak

cluster:
  name: prodbox-keycloak-pg
  instances: 3
  crVersion: "2.9.0"

image:
  postgres:
    repository: 127.0.0.1:30080/prodbox/percona-distribution-postgresql-mirror
    tag: "17.9-1"
  pgBouncer:
    repository: 127.0.0.1:30080/prodbox/percona-pgbouncer-mirror
    tag: "1.25.1-1"
  pgBackRest:
    repository: 127.0.0.1:30080/prodbox/percona-pgbackrest-mirror
    tag: "2.58.0-1"

postgres:
  version: 17
  database: keycloak
  username: keycloak

secrets:
  application:
    name: prodbox-keycloak-pg-pguser-keycloak
    username: keycloak
    password: change-me
  superuser:
    name: prodbox-keycloak-pg-pguser-postgres
    username: postgres
    password: change-me
  standby:
    name: prodbox-keycloak-pg-primaryuser
    username: primaryuser
    password: change-me

storage:
  className: manual
  size: 20Gi

security:
  runAsUser: 1001
  runAsGroup: 1001
  fsGroup: 1001

proxy:
  pgBouncerReplicas: 0

backups:
  enabled: false

podAntiAffinity:
  enabled: true
