apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: vscode
  labels:
    {{- include "vscode.labels" . | nindent 4 }}
  annotations:
    cert-manager.io/cluster-issuer: {{ .Values.ingress.clusterIssuer | quote }}
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - {{ .Values.ingress.host | quote }}
      secretName: vscode-tls
  rules:
    - host: {{ .Values.ingress.host | quote }}
      http:
        paths:
          - path: /oauth2
            pathType: Prefix
            backend:
              service:
                name: vscode-auth-proxy
                port:
                  number: 4180
          - path: /auth
            pathType: Prefix
            backend:
              service:
                name: keycloak
                port:
                  number: 8080
          - path: /
            pathType: Prefix
            backend:
              service:
                name: vscode-auth-proxy
                port:
                  number: 4180
