apiVersion: v1
kind: Secret
metadata:
  name: vscode-nginx
  labels:
    {{- include "vscode.nginxLabels" . | nindent 4 }}
type: Opaque
stringData:
  OIDC_CLIENT_SECRET: {{ .Values.nginx.clientSecret | quote }}
