apiVersion: v1
kind: Secret
metadata:
  name: vscode-auth-proxy
  labels:
    {{- include "vscode.oauth2ProxyLabels" . | nindent 4 }}
type: Opaque
stringData:
  OAUTH2_PROXY_CLIENT_SECRET: {{ .Values.oauth2Proxy.clientSecret | quote }}
  OAUTH2_PROXY_COOKIE_SECRET: {{ .Values.oauth2Proxy.cookieSecret | quote }}
