apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ printf "%s-secret-materializer" .Values.oidc.securityPolicyName | quote }}
  labels:
    {{- include "vscode.labels" . | nindent 4 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ printf "%s-secret-materializer" .Values.oidc.securityPolicyName | quote }}
  labels:
    {{- include "vscode.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["create"]
  - apiGroups: [""]
    resources: ["secrets"]
    resourceNames:
      - {{ printf "%s-client" .Values.oidc.securityPolicyName | quote }}
    verbs: ["get", "update", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ printf "%s-secret-materializer" .Values.oidc.securityPolicyName | quote }}
  labels:
    {{- include "vscode.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ printf "%s-secret-materializer" .Values.oidc.securityPolicyName | quote }}
    namespace: {{ .Release.Namespace | quote }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ printf "%s-secret-materializer" .Values.oidc.securityPolicyName | quote }}
