apiVersion: v1
kind: Service
metadata:
  name: vscode
  labels:
    {{- include "vscode.labels" . | nindent 4 }}
spec:
  selector:
    app.kubernetes.io/name: vscode
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - name: http
      port: 8080
      targetPort: http
---
apiVersion: v1
kind: Service
metadata:
  name: vscode-auth-proxy
  labels:
    {{- include "vscode.oauth2ProxyLabels" . | nindent 4 }}
spec:
  selector:
    app.kubernetes.io/name: vscode-auth-proxy
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - name: http
      port: 4180
      targetPort: http
